//using Google.Protobuf;

//namespace ProtocolBufferExample
//{
//    // Generated by the protocol buffer compiler. DO NOT EDIT!
//    // source: user.proto


//    public sealed class User : IMessage<User>
//    {
//        public int Id { get; set; }
//        public string Name { get; set; }
//        public string Email { get; set; }



//        // Serialization methods
//        public void WriteTo(CodedOutputStream output) { /*...*/ }
//        public int CalculateSize() { /*...*/ }
//        public void MergeFrom(CodedInputStream input) { /*...*/ }

//        // Parsing methods
//        public static User ParseFrom(byte[] data) { /*...*/ }
//        public static User ParseFrom(CodedInputStream input) { /*...*/ }

//        public void MergeFrom(User message)
//        {
//            throw new NotImplementedException();
//        }

//        public bool Equals(User? other)
//        {
//            throw new NotImplementedException();
//        }

//        public User Clone()
//        {
//            throw new NotImplementedException();
//        }
//    }

//}
